### ISSUE TITLE
Bug: Route ID Collision difference from v1 routes

### ISSUE THREAD

**Issue by MattyBalaam** [remix-run/v1-compat-utils#36]
As far as I understand it this should be a valid layout v1 convention:

- auth
  - login.tsx `site.com/login.tsx`
- dashboard
  -  index.tsx `site.com/`
  -  about.tsx `site.com/about`
- __auth.tsx 
- __dashboard.tsx 

However when using this package to keep compatibility to move to v2 elsewhere we get an error:

<img width="538" alt="Screenshot 2023-10-30 at 11 24 22" src="https://github.com/remix-run/v1-compat-utils/assets/1246923/505d2e3d-25b8-453f-9413-e9365ce8901c">

**Comment by MattyBalaam** [comment]
Aha, that was it, we had this setup already as  `['**/*',…]`. Thank you.

**Comment by na2hiro** [comment]
https://remix.run/docs/en/main/start/v2#upgrading-without-changing-files

It'd be nice if that's added to this section in the v2 migration guide
